version: 2.1

orbs:
  npm: sugarshin/npm@0.1.5

commands:
  run-tests:
    steps:
      - run:
          name: Create Report directories
          command: |
              mkdir -p test-results/ava
              mkdir -p test-results/eslint
      - run:
          name: Lint
          command: npm run ci:lint --silent > test-results/eslint/results.xml
      - run:
          name: Test
          command: npm run ci:test --silent > test-results/ava/results.xml
      - run:
          name: Test
          command: |
              npm run ci:coverage-report
              npm run ci:coverage-check
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - store_artifacts:
          path: coverage


executors:
  nodejs:
    docker:
      - image: 'circleci/node:10.16.0'

jobs:
  build:
    executor: nodejs
    steps:
      # todo: Collect coverage
      - checkout
      - npm/install # Contains a checkout step (optional)
      - run-tests
  publish:
    executor: nodejs
    steps:
      - npm/install # todo; cache and restore dist.

workflows:
  publish:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
